#server:
#port 8080
#pring.redis.database=0
## Redis服务器地址
#spring.redis.host=127.0.0.1
## Redis服务器连接端口
#spring.redis.port=6379
## Redis服务器连接密码（默认为空）
#spring.redis.password=
## 链接超时时间 单位 ms（毫秒）
#spring.redis.timeout=3000
################# Redis 线程池设置 ##############
## 连接池最大连接数（使用负值表示没有限制） 默认 8
#spring.redis.lettuce.pool.max-active=8
## 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
#spring.redis.lettuce.pool.max-wait=-1
## 连接池中的最大空闲连接 默认 8
#spring.redis.lettuce.pool.max-idle=8
## 连接池中的最小空闲连接 默认 0
#spring.redis.lettuce.pool.min-idle=0
nacos:
  config:
    server-addr: 127.0.0.1:8848
    data-id: spring-cloud-dev
    namespace: 5e1b94a2-2fb4-425e-8058-27341eddf452
    auto-refresh: true
    bootstrap:
      enable: true
#  discovery:
#    server-addr: 127.0.0.1:8848
#    auto-register: true
#    register:
#      enabled: true
#      ephemeral: true
#      groupName: boot
#      healthy: true
#      clusterName: springboot
#      weight: 0.6D
#    namespace: 5e1b94a2-2fb4-425e-8058-27341eddf452


spring:
  application:
    name: redisserver
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
      cache:
        enabled: false
      enabled: true
    nacos:
     discovery:
      server-addr: 127.0.0.1:8848
      auto-register: true
      namespace: 5e1b94a2-2fb4-425e-8058-27341eddf452
      register:
        enabled: true
        healthy: true
        ephemeral: true
        clusterName: springboot
        groupName: DEFAULT_GROUP
        weight: 1
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000




