spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
      cache:
        enabled: true
      enabled: true
    nacos:
     discovery:
      server-addr: 47.92.235.151:8848
      auto-register: true
      namespace:
      register:
        enabled: true
        healthy: true
        ephemeral: true
        clusterName: springboot
        groupName: DEFAULT_GROUP
        weight: 1
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000


logging:
  config: classpath:logback-custom.xml


